name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-01:

    runs-on: windows-latest

    steps:      
    - name: Where Am I
      shell: cmd
      run: ls -la
  
  job-02:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Where Am I
      shell: cmd
      run: ls -la
