name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-01:

    runs-on: windows-latest

    steps:      
    - name: Where Am I
      shell: cmd
      run: tree /f
  
  job-02:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Where Am I
      shell: cmd
      run: tree /f

  job-03:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore  --configuration Release
    - name: Where Am I
      shell: cmd
      run: tree /f
      
  job-04:

    runs-on: windows-latest

    steps:      
    - name: Where Am I
      shell: cmd
      run: tree /f
  
  job-05:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Where Am I
      shell: cmd
      run: tree /f
